apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: example-app

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - virtualservice.yaml
  - authorization-policy.yaml

commonLabels:
  app.kubernetes.io/name: example-app
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: cat-herding-apps
