---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - virtualservice.yaml
  - configmap-web.yaml

labels:
  - pairs:
      app.kubernetes.io/name: example-app
      app.kubernetes.io/component: web-application

