---
# AuthorizationPolicy to allow traffic to example-app
# Since ext_authz is globally applied via EnvoyFilter, we just need to ALLOW traffic here
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: example-app-allow
  namespace: default
  labels:
    app: example-app
    app.kubernetes.io/name: example-app
spec:
  # Apply to example-app pods
  selector:
    matchLabels:
      app: example-app
  
  # ALLOW action - ext_authz will still be enforced by EnvoyFilter at gateway
  action: ALLOW
  
  rules:
  # Allow all traffic - auth is handled by ext_authz at gateway level
  - {}
