{{- if .Values.istio.enabled }}
{{- if .Values.istio.gateway.create }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.istio.gateway.name }}
  namespace: {{ .Values.istio.ingressGateway.namespace }}
  labels:
    {{- include "oauth2-sidecar.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingress
spec:
  selector:
    {{- toYaml .Values.istio.ingressGateway.selector | nindent 4 }}
  servers:
    {{- if .Values.istio.gateway.httpsRedirect }}
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        {{- range .Values.istio.gateway.hosts }}
        - {{ tpl . $ | quote }}
        {{- end }}
      tls:
        httpsRedirect: true
    {{- end }}
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        {{- range .Values.istio.gateway.hosts }}
        - {{ tpl . $ | quote }}
        {{- end }}
      tls:
        mode: {{ .Values.istio.gateway.tls.mode }}
        {{- if .Values.istio.gateway.tls.credentialName }}
        credentialName: {{ .Values.istio.gateway.tls.credentialName }}
        {{- end }}
        {{- if .Values.istio.gateway.tls.minProtocolVersion }}
        minProtocolVersion: {{ .Values.istio.gateway.tls.minProtocolVersion }}
        {{- end }}
{{- end }}
{{- end }}
